### ISSUE TITLE
Cancel job is broken

### ISSUE THREAD

**Issue by emartgu** [zencoder/zencoder-java#14]
When calling ZencoderClient.cancelJob(jobId), the job is not canceled but resubmitted.

In ZencoderClient.cancelJob(jobId):
String url = api_url + "/jobs/" + id + "/resubmit.json";

Should be:
String url = api_url + "/jobs/" + id + "/cancel.json";

**Comment by skidder** [comment]
This issue was fixed in commit 54d1f27915dc70e2380940ce79c96ff08759ba9a which is reflected in the latest version of library, currently 2.0.19
