### ISSUE TITLE
SegmentingType problems

### ISSUE THREAD

**Issue by mdeimel** [zencoder/zencoder-java#19]
There are two different issues when creating a `ZencoderOutput`, as it relates to the `SegmentingType`.

1. The `SegmentingType` only includes an enum value for `hls` and `mms`, but there is no `dash`, which is available in the `prepare_for_segmenting` JSON attribute for an `output`.

2. When creating a `ZencoderOutput` object, I should be able to specify multiple output types, either as a comma separated string (as shown [here](https://app.zencoder.com/docs/api/encoding/segmented-streaming/prepare-for-segmenting?from_query=prepare_for_segmenting)), or as an array (as shown [here](https://app.zencoder.com/docs/guides/encoding-settings/dash?from_query=dash)). Perhaps an `addPrepareForSegmenting()` method should be added, instead of just `setPrepareForSegmenting()`.

Thank you.

**Comment by skidder** [comment]
Pull-request #21 has been merged, marking as closed.  Thank you for filing an issue and providing a fix!
