### ISSUE TITLE
SegmentedStream does not contain a `source` attribute

### ISSUE THREAD

**Issue by mdeimel** [zencoder/zencoder-java#20]
The `SegmentedStream` class does not have a `source` attribute, even though one exists in the JSON - as seen [here](https://app.zencoder.com/docs/api/encoding/segmented-streaming/streaming-source).

I've worked around this for now by extending the `SegmentedStream` class, and adding a `source` attribute - which does work. I can submit a pull request for a fixed `SegmentedStream` if that would be helpful.

Thanks.

**Comment by skidder** [comment]
Pull-request #21 has been merged, marking as closed.  Thank you for filing an issue and providing a fix!
